site_name: resop docs
site_url: https://cnsc-dev.pages.in2p3.fr/resop/
site_dir: public
theme: 
  name: material
  palette:
    scheme: default
    primary: amber
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/daviderovell0/resop
repo_name: daviderovell0/resop


markdown_extensions:
- toc:
    permalink: "#"

nav:
  - Home: 'index.md'
  - Install: 
    - Installation: 'install/install.md'
    - Deployment: 'install/deploy.md'
  - Use:
    - Overview: 'use/overview.md'
    - Authentication: 'use/auth.md'
    - Usage: 'use/usage.md'
    - Customise: 'use/implementation.md'
  - Reference: 'reference.md'
  - Develop:
    - Implementation: 'develop/implementation.md'
    - Dev cluster: 'develop/vagrantcluster.md'
    - Development Guide: 'develop/development.md'
